export const UserActionTypes = {
  SELECT_USER: "SELECT_USER",
  USER_LOGIN: "USER_LOGIN",
  GET_USERS: "GET_USERS",
  POST_USER: "POST_USER",
  DELETE_USER: "DELETE_USER",
  UPDATE_USER: "UPDATE_USER",
};
