export const UserActionTypes = {
  SELECT_USER: "SELECT_USER",
  USER_LOGIN: "USER_LOGIN",
  USER_LOG_OUT: "USER_LOG_OUT",
  GET_USERS: "GET_USERS",
  POST_USER: "POST_USER",
  DELETE_USER: "DELETE_USER",
  UPDATE_USER: "UPDATE_USER",
  UPDATE_USER_AMOUNT: "UPDATE_USER_AMOUNT",
};
